-- INSERTS de notícias pesquisadas com categorias específicas

INSERT INTO news (title, description, link, image, category, decade, year, is_featured) 
VALUES 
('Chacina de Ácari', 'Caso ocorrido no Rio de Janeiro, envolvendo o desaparecimento de 11 jovens. Supostamente mortos por policiais, o caso evidenciou questões de violência policial e omissão estatal, gerando repercussão internacional e pedidos de justiça por parte das famílias das vítimas.', 'https://g1.globo.com/jornal-nacional/noticia/2024/12/04/chacina-de-acari-corte-interamericana-responsabiliza-brasil-pelo-desaparecimento-de-11-jovens-no-rio.ghtml', 'https://pbs.twimg.com/media/FYnV_70X0AANwOs.jpg', 'Chacina', '90', 1990, false),

('Caso da menina Míriam', 'O desaparecimento e a morte da menina Míriam Brandão chocaram o Brasil em 1992. O caso expôs a brutalidade e a violência contra crianças, mobilizando a opinião pública e gerando questionamentos sobre a segurança infantil, além de deixar marcas profundas na memória coletiva.', 'https://www.em.com.br/app/noticia/gerais/2011/09/02/interna_gerais,248406/assassino-que-chocou-a-capital-em-1992-esta-proximo-da-liberdade.shtml', 'https://img.r7.com/images/r7-estudio-1990-a-decada-do-crime-24112022154352302?&no_crop=true', 'Homicídio', '1990s', 1992, false),

('Caso Daniella Perez', 'O assassinato da atriz Daniella Perez em 1992, cometido por um colega de elenco, gerou grande comoção nacional. O crime foi amplamente coberto pela mídia e desencadeou um debate sobre feminicídio, culminando em mudanças legislativas significativas e homenagens à memória da jovem atriz.', 'https://www.cnnbrasil.com.br/entretenimento/daniella-perez-assassinato-de-atriz-completa-32-anos-relembre-o-caso/L', 'https://s2-oglobo.glbimg.com/cW6BerL4pb_WXtZd550OYmPyIBU=/0x0:5545x3372/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2022/E/L/FdCKeyTmaQxLHI5atsHA/61507276-rio-de-janeiro-rj-11-11-1992-televisao-rj-tv-globo-novela-de-corpo-e-alma-g.jpg', 'Feminicídio', '90', 1992, true),

('Caso Maníaco do Parque', 'Francisco de Assis Pereira, o Maníaco do Parque, aterrorizou São Paulo no final dos anos 1990 com uma série de assassinatos brutais. Ele atraía mulheres ao parque sob falsos pretextos e as assassinava, chocando o país e desencadeando uma caçada policial que revelou seu histórico de crimes e abusos.', 'https://www.cnnbrasil.com.br/nacional/relembere-o-caso-do-maniaco-do-parque-tema-de-filme-que-estreia-hoje/', 'https://img.r7.com/images/r7-estudio-1990-a-decada-do-crime-24112022154355697?&no_crop=true', 'Assassinato em série', '90', 1998, true),

('Caso atirador do shopping', 'Em 1998, um atirador abriu fogo em um shopping center no Brasil, deixando vítimas e espalhando pânico entre os frequentadores. O caso trouxe à tona discussões sobre segurança em locais públicos e o controle de armas, além de gerar investigações para entender as motivações do agressor.', 'https://www.cnnbrasil.com.br/nacional/atirador-do-shopping-morumbi-em-sp-deixa-prisao-apos-25-anos-entenda/', 'https://img.r7.com/images/r7-estudio-1990-a-decada-do-crime-24112022154353116?dimensions=780x340', 'Homicídio', '90', 1998, false);


-- INSERTS de notícias pesquisadas de casos recentes

INSERT INTO news (title, description, link, image, category, decade, year, is_featured) 
VALUES 
('Caso do comerciante Igor Peretto', 'O caso do assassinato do comerciante Igor Peretto ocorreu em 31 de agosto de 2024. A vítima foi morta a facadas por Mário Vitorino, que teria sido incentivado por Rafaela Costa e Marcelly, esposa e irmã da vítima. As mulheres foram presas em 6 de setembro e Mário foi capturado em 15 de setembro, escondido na casa de um parente.', 'https://s2-g1.glbimg.com/JvhWoIpsq_9psv4aLok2MHcJYrA=/0x0:1200x800/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2024/g/E/Ew0xjMQzCdBxGupwVeyw/crime-igor.jpg', 'https://s2-g1.glbimg.com/tDtHqbi2ATdsnc_Y_dgejmi1sYI=/0x0:1200x800/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2024/X/S/icFN1mQA2nFYPPsesJeg/mario-marcelly-faca.jpg', 'Homicídio', '2020s', 2024, true),

('Caso da trapezista argentina', 'Em dezembro de 2023, Florencia Aranguren foi brutalmente assassinada a facadas enquanto passeava com o cachorro em Búzios, RJ. Carlos José foi preso em flagrante e condenado a 33 anos de prisão. O corpo da trapezista foi encontrado em uma trilha e o cão permaneceu ao lado da vítima até a chegada das autoridades.', 'https://www.condorcontabilidade.com.br/nb2/rj/regiao-dos-lagos/noticia/2025/04/03/julgamento-marcado-acusado-de-matar-trapezista-argentina-em-buzios-enfrenta-o-tribunal-do-juri-no-dia-9-de-abril.ghtml', 'https://www.condorcontabilidade.com.br/nb2/rj/regiao-dos-lagos/noticia/2025/04/03/julgamento-marcado-acusado-de-matar-trapezista-argentina-em-buzios-enfrenta-o-tribunal-do-juri-no-dia-9-de-abril.ghtml', 'Homicídio', '2020s', 2023, false),

('Caso do menino arremessado da ponte pelo pai', 'Em março de 2025, um homem arremessou o próprio filho de cinco anos de uma ponte em São Gabriel, RS, em um ato de vingança contra a ex-esposa. Ele confessou o crime e está preso.', 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/03/cantor-afogado-pe-2-2.jpg?w=1115', 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/03/cantor-afogado-pe-2-2.jpg?w=1115', 'Homicídio', '2020s', 2025, false),

('Caso do motorista de app em SP', 'Em março de 2025, um motorista de aplicativo foi preso após tentar estuprar e roubar uma passageira de 21 anos no bairro da Casa Verde, zona norte de São Paulo. A vítima conseguiu fugir e o homem foi preso.', 'https://s2-g1.glbimg.com/JTYtBLWhlDV-pnM6l5rMDQd31mc=/1280x0/filters:format(jpeg)/https://thumbor.globoi.com/unsafe/fit-in/1280x720/s03.video.glbimg.com/deo/vi/54/13/13491354', 'https://s2-g1.glbimg.com/JTYtBLWhlDV-pnM6l5rMDQd31mc=/1280x0/filters:format(jpeg)/https://thumbor.globoi.com/unsafe/fit-in/1280x720/s03.video.glbimg.com/deo/vi/54/13/13491354', 'Violência Sexual', '2020s', 2025, false),

('Caso Clara Maria em MG', 'Em março de 2025, Clara Maria, de 21 anos, foi encontrada morta e concretada em uma casa em Belo Horizonte. Os suspeitos Thiago e Pimentel foram presos após confessarem o crime.', 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/03/Clara-Maria.jpg?w=880', 'https://s2-g1.glbimg.com/rhQd61z61dAkd5T2vboR-uWX7B8=/0x0:1022x592/600x0/smart/filters:gifv():strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/m/D/C8rfRRQRGhT0NFJMBGUQ/suspeitos-clara-maria.jpg', 'Homicídio', '2020s', 2025, false),

('Caso do cantor morto afogado em PE', 'Em fevereiro de 2025, um cantor foi encontrado morto após se afogar em um rio em Pernambuco. A polícia investiga as circunstâncias do afogamento e se houve envolvimento de terceiros.', 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/03/cantor-afogado-pe-2-2.jpg?w=1115', 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/03/cantor-afogado-pe-2-2.jpg?w=1115', 'Morte Suspeita', '2020s', 2025, false),

('Filho mata pai alcoólatra em SC', 'Em fevereiro de 2025, um homem de 23 anos matou o pai de 47 anos a golpes de tesoura em São João Batista, SC. A vítima foi encontrada com 22 perfurações. O suspeito se entregou à polícia após o crime.', 'https://static.ndmais.com.br/2025/02/identificado-homem-morto-por-filho-a-tesouradas-sao-joao-batista-grande-florianopolis-elvis-marcos-da-silva-800x467.jpg', 'https://static.ndmais.com.br/2025/01/adalberto-fugitivo-presidio-florianopolis-550x310.png', 'Homicídio', '2020s', 2025, false),

('Policial mata esposa e enteada durante Réveillon', 'Em janeiro de 2025, um policial penal matou a companheira e a enteada de 13 anos em Três Marias, MG. O suspeito tirou a própria vida após o crime. A motivação estaria ligada a uma discussão familiar.', 'https://s2-g1.glbimg.com/jrXuIuAs0fASIBRdA6-ZBApkasI=/0x0:1700x1065/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/Y/I/VLtRPSSjap7CQwdfzhJg/foto-g1-2-.png', 'https://s2-g1.glbimg.com/jrXuIuAs0fASIBRdA6-ZBApkasI=/0x0:1700x1065/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/Y/I/VLtRPSSjap7CQwdfzhJg/foto-g1-2-.png', 'Homicídio', '2020s', 2025, false);
