-- INSERTS de notícias pesquisadas anos 1970

INSERT INTO news (title, description, link, image, category, decade, year, is_featured) 
VALUES 
('Caryn Campbell, uma das vítimas de Ted Bundy, estava de férias com sua família em seu hotel quando Bundy a sequestrou.', 'Campbell tinha apenas 23 anos quando desapareceu do resort onde estava passando um tempo no Colorado. A família veio de Chicago para passar um tempo agradável, mas tudo acabou sendo muito ruim.
Ela disse ao seu noivo, que estava com seus filhos, que iria para o quarto pegar uma revista para ler no saguão do resort perto de uma lareira.
Ela nunca voltou para o quarto porque quando seu noivo e as crianças foram até o quarto para ver o que ela estava fazendo, eles viram a revista no mesmo lugar onde Caryn a havia deixado mais cedo naquele dia.
Ninguém sabe como Bundy conseguiu fazer isso em um resort onde as pessoas estão constantemente entrando e saindo. Ele provavelmente inventou uma história, talvez dizendo a ela que não conseguia tirar os esquis de seus filhos do topo do carro porque tinha um gesso no braço.
Seu corpo foi descoberto pouco antes da namorada de Bundy e sua filha irem visitá-lo. Durante essa visita, ela acreditava que Ted Bundy era o "Ted" de Washington, pois após sua mudança, duas mulheres foram assassinadas em uma área de baixo índice de criminalidade. Por alguma razão, ela não foi embora e deixou sua filha com Bundy.
', 'https://www.reddit.com/r/serialkillers/comments/1794p7g/caryn_campbell_one_of_ted_bundys_victims_was_on/?tl=pt-br', 'https://preview.redd.it/pp26p25s4kub1.jpg?width=640&crop=smart&auto=webp&s=d41e9de0739c1a10aba95b9ec0301af1dfda45d7', 'Homicídio', '75', 1975, false),

('Há 50 anos, Lynda Ann Healy foi sequestrada e assassinada por Ted Bundy. Ela tinha 21 anos e acredita-se que foi sua primeira vítima.', 'Aos 21 anos, Lynda Ann Healey estudava na UW e era a garota do tempo da rádio local. Quando a jovem desapareceu, em fevereiro de 1974, seus amigos acionaram a polícia que encontrou sangue em seus lençóis e travesseiros.
A perícia encontrou ainda sua camisola pendurada no armário e um anel ensanguentado, mas notaram que faltavam algumas roupas, sua fronha e mochila. Deduziram que a pessoa que havia sequestrado Healey, possivelmente retirou as suas roupas e a vestiu com outras limpas.
A jovem ficou 14 meses desaparecida, até que seus ossos do crânio e da mandíbula foram encontrados em Taylor Mountain, à uma hora de sua casa.
', 'https://aventurasnahistoria.com.br/noticias/vitrine/historia-as-vitimas-esquecidas-de-ted-bundy.phtml', 'https://m.media-amazon.com/images/M/MV5BYTc1YTdkMGMtYmE4MC00OWY4LTk2ODMtYzNlMjgzN2Q1OTYwXkEyXkFqcGc@._V1_.jpg', 'Homicídio', '74', 1974, false),

('Em memória de Kimberly Leach, 12, a última vítima de Ted Bundy:  mundo perdeu uma grande alma
', 'Kimberly Leach , uma aluna do sétimo ano em Lake City, Flórida, desapareceu no meio do dia escolar em 9 de fevereiro de 1978.
"Estava chovendo, garoando, (um) dia muito triste", disse a amiga de infância e colega de classe Lisa Little. "Fui ao nosso local designado para nos encontrarmos para irmos para a nossa aula juntos e ela não estava lá."
A polícia de Lake City procurou por Kimberly, mas não encontrou nada. As autoridades pediram ao público que se apresentasse com qualquer informação.
Antes de Kimberly ser encontrada, a polícia de Pensacola prendeu Ted Bundy , um sequestrador condenado, suspeito de assassinato e fugitivo na lista dos mais procurados do FBI.
Ele escapou das autoridades do Colorado duas vezes em 1977 — uma vez pulando da janela de um tribunal e depois escapando de uma cela de prisão.
Cerca de dois meses após o desaparecimento de Kimberly, em abril de 1978, seu corpo foi encontrado . Ela havia sido agredida e assassinada e então colocada em um pequeno galpão em uma área arborizada atrás do Suwannee River State Park.
', 'https://aventurasnahistoria.com.br/noticias/vitrine/historia-as-vitimas-esquecidas-de-ted-bundy.phtml', 'https://s.abcnews.com/images/US/ted-bundy-victim-kimberly-leach-gty-jc-190212_hpEmbed_8x9_992.jpg', 'Homicídio', '78', 1978, true),

('Quem ama não mata: o feminicídio de 1976 que ajudou a mudar a Justiça brasileira', 'No dia 1º de agosto de 2023, o caso da socialite mineira Ângela Maria Fernandes Diniz, morta a tiros em 1976 pelo namorado, o playboy paulista Raul Fernando do Amaral Street, conhecido como Doca Street, foi citado pelos ministros Luís Roberto Barroso e Cármen Lúcia durante uma sessão do Supremo Tribunal Federal.
No dia 1º de agosto de 2023, o caso da socialite mineira Ângela Maria Fernandes Diniz, morta a tiros em 1976 pelo namorado, o playboy paulista Raul Fernando do Amaral Street, conhecido como Doca Street, foi citado pelos ministros Luís Roberto Barroso e Cármen Lúcia durante uma sessão do Supremo Tribunal Federal.
', 'https://g1.globo.com/rj/rio-de-janeiro/noticia/2023/09/16/quem-ama-nao-mata-o-feminicidio-de-1976-que-ajudou-a-mudar-a-justica-brasileira.ghtml', 'https://s2-g1.glbimg.com/EAoaCfzNqe--luX2gMijvbzxe-k=/0x0:538x303/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2023/X/9/BBiLQcQZ6P4dU9f51QPw/angela-1-credito-arquivo-do-processo-judicial.jpg', 'Feminicídio', '76', 1976, true),

('Caso Carlinhos', 'Aos 77 anos, Conceição lembra de um evento trágico que mudou sua família para sempre. Em uma noite, enquanto estava em casa com cinco de seus sete filhos na Rua Alice, no Rio de Janeiro, as luzes se apagaram. A mais velha, Vera Lúcia, saiu para consertar a caixa de luz e foi surpreendida por um homem armado. O invasor exigiu a criança mais nova, Carlinhos, que foi levado chorando por ele. Conceição tentou acalmar o menino enquanto o sequestrador deixava um bilhete pedindo 100 mil cruzeiros, que era uma quantia significativa na época, em troca do retorno de Carlinhos. 
Desde esse dia, em 2 de agosto de 1973, o destino de Carlinhos permanece desconhecido e a família ainda busca respostas. Embora muitos especulem sobre seu desaparecimento, incluindo a possibilidade de que Carlinhos tenha sobrevivido, sua ausência causa angústia. A polícia investigou várias teorias, incluindo uma suposta farsa criada pelo pai de Carlinhos, João Mello da Costa, para conseguir dinheiro, mas nada foi provado. A situação se complicou ainda mais com a prisão de uma funcionária de João, que confessou ter sequestrado o menino, mas foi liberada rapidamente e o caso ficou sem progresso. 
A investigação tomou um novo rumo em janeiro de 1974, quando Adilson de Oliveira confessou o sequestro e acusou João de ser o mandante. Entretanto, falta de provas fez com que João fosse liberado no dia seguinte, e logo foi descoberto que a confissão era falsa. O inquérito ficou parado por anos, só sendo enviado à Justiça quatro anos após o crime. A separação dos pais de Carlinhos ocorreu um ano depois do desaparecimento, alimentada pela desconfiança de Conceição sobre o envolvimento de João.
O caso ganhou novas evidências quando um detetive particular apontou novamente João como mandante, e exames mostraram que o bilhete de resgate foi escrito por Silvio Pereira, funcionário da empresa de João. A filha Vera reconheceu Silvio durante o sequestro, mas João ignorou essa informação. Apesar de Silvio ter sido condenado a 13 anos de prisão, ele foi absolvido posteriormente por falta de provas. 
Conceição sempre nutria dúvidas sobre o que realmente aconteceu naquela noite e acreditava que João pudesse estar envolvido, mas a polícia não deu ouvidos a suas preocupações. Hoje, João vive com sua segunda esposa e não comenta sobre o desaparecimento do filho. A dor da perda permanece, e Conceição ainda espera, com fé, que um dia saiba a verdade sobre Carlinhos.', 'https://oglobo.globo.com/rio/dez-crimes-que-chocaram-rio-de-janeiro-17845895', 'https://s2-oglobo.glbimg.com/uiRGc_uaXEtQ5oMA8XHXJJaNCwk=/0x0:648x581/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2024/c/l/dIuV18SemrqJeh7b8gPg/captura-de-tela-2024-04-06-204447.jpg', 'Assassinato', '73', 1973, false);

-- INSERTS de notícias pesquisadas anos 2020

INSERT INTO news (title, description, link, image, category, decade, year, is_featured) 
VALUES 
('Família encontrada carbonizada no ABC: o que se sabe e o que falta saber', 'Na madrugada de 28 de janeiro, os bombeiros encontraram corpos carbonizados de três pessoas de uma mesma família em um carro em chamas na área rural de São Bernardo do Campo, no ABC Paulista.
As vítimas são os empresários Flaviana e Romuyuki Gonçalves e o filho caçula deles, o adolescente Juan Victor. Todos moravam em uma casa em um condomínio fechado em Santo André, também no ABC. Os três foram torturados e mortos, possivelmente em decorrência de coronhadas, segundo a investigação.
A polícia investiga o envolvimento de cinco pessoas no crime. Entre elas, estão a filha mais velha do casal, Ana Flávia, e a namorada dela, Carina de Abreu. As duas estão na cadeia, assim como os irmãos Juliano de Oliveira Ramos Júnior e Jonathan Fagundes Ramos, que são primos de Carina. Também está preso Guilherme Ramos da Silva.
', 'https://g1.globo.com/sp/sao-paulo/noticia/2020/02/05/familia-encontrada-carbonizada-no-abc-o-que-se-sabe-e-o-que-falta-saber.ghtml', 'https://s2-g1.glbimg.com/swOzblxH-ySGR9zsG1N9gDwtv2E=/1280x0/filters:format(jpeg)/https://s04.video.glbimg.com/x720/8288631.jpg', 'Homicídio', '2020', 2020, true),

('Caso Miguel: como foi a morte do menino que caiu do 9º andar de prédio no Recife', 'O menino Miguel Otávio Santana da Silva, de 5 anos, morreu após cair do 9º andar de um prédio de luxo em Recife na última terça-feira (2). Ele estava aos cuidados da patroa de sua mãe, a primeira-dama de Tamandaré, Sari Corte Real, enquanto a mãe passeava com o cachorro dos patrões. 
A patroa foi presa por homicídio culposo, mas liberada após pagar fiança de R$20 mil. A mãe, Mirtes, contou que viu Miguel vivo, mas com dificuldade para respirar. Ele foi levado para o hospital, onde foi informado que não sobreviveu. 
Miguel acompanhou a mãe ao trabalho porque estava sem aulas devido às medidas de quarentena contra a Covid-19. Ele não pôde ficar com a avó porque ela tinha compromissos. Enquanto a mãe estava embaixo do prédio, Miguel quis encontrá-la. 
Durante o velório, Mirtes encontrou Sari e Sérgio, os patrões, sem saber o que tinha acontecido. Depois, Mirtes recebeu imagens das câmeras de segurança e ficou revoltada ao ver seu filho sozinho no elevador. Sari aparentemente apertou um botão do elevador, mas afirmou que não o fez. Em carta divulgada, Sari pediu perdão a Mirtes, expressando solidariedade ao seu sofrimento.', 
'https://g1.globo.com/sp/sao-paulo/noticia/2020/02/05/familia-encontrada-carbonizada-no-abc-o-que-se-sabe-e-o-que-falta-saber.ghtml', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQELjHpSeuAS6NriHi0tm6_DbnNh-92Ev04Bg&s', 'Homicídio', '2020', 2020, true),

('Caso Isabele: amiga que matou adolescente de 14 anos em MT é indiciada junto com namorado, pai e sogro', '
A polícia concluiu o inquérito sobre a morte de Isabele Ramos Guimarães, de 14 anos, em um condomínio de luxo, em Cuiabá, no dia 12 de julho. O documento aponta que a amiga, também de 14 anos, que atirou no rosto dela, deve responder por ato infracional por homicídio doloso, quando há intenção de matar , imprudência e imperícia.
O delegado Wagner Bassi, da Delegacia de Homicídios e Proteção à Pessoa (DHPP), que conduziu a investigação, afirmou, em entrevista coletiva, nesta quarta-feira (2), que a versão apresentada por ela, no decorrer do inquérito, era incompatível com o que aconteceu no dia da morte e que a conduta dela foi dolosa, porque, no mínimo, assumiu o risco de matar a vítima.
Além da adolescente, o namorado dela, de 16 anos, também vai responder por ato infracional análogo ao porte ilegal de arma de fogo, porque transitou armado, sem autorização. Ele tem 16 anos e levou as armas para a casa da namorada. O tiro que matou Isabele partiu de uma dessas armas de fogo, que pertencia ao pai do jovem.
Por causa disso, o pai dele também foi indiciado. Segundo o delegado, mesmo tendo alegado que não tinha conhecimento de que as armas tinham sido levadas pelo filho para o local, ele foi indiciado por omissão de cautela na guarda de arma de fogo, já que teria obrigação de guardar as armas em local seguro.
', 'https://g1.globo.com/mt/mato-grosso/noticia/2020/09/02/investigacao-policial-sobre-morte-de-adolescente-em-cuiaba-responsabiliza-amiga-que-disparou-namorado-dela-e-indicia-pai-e-sogro.ghtml', 'https://s2-g1.glbimg.com/L-Ke8jsj94siAI-WKauZ4BX-L1k=/0x0:412x448/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/3/I/xAfxa6SOaSjmcWUieAQQ/whatsapp-image-2020-07-13-at-08.03.01.jpeg', 
'Homicídio', '2020', 2020, false),

('Menina de 10 anos estuprada pelo tio no Espírito Santo tem gravidez interrompida', 'A menina de 10 anos que engravidou após ser estuprada em São Mateus, no Espírito Santo, passou por um procedimento e interrompeu nesta segunda-feira (17) a gravidez em um hospital de referência em Pernambuco. Ela estava na unidade desde domingo (16), quando iniciou o processo. De acordo com a direção do hospital, a menina passa bem.
Em nota, a Secretaria de Saúde de Pernambuco afirmou que o procedimento foi feito com autorização judicial do Espírito Santo. A unidade que atendeu a menina é referência estadual nesse tipo de procedimento e de acolhimento às vítimas. O texto aponta ainda que "todos os parâmetros legais estão sendo rígidamente seguidos".
O procedimento feito na menina de 10 anos foi concluído por volta das 11h. A gravidez foi revelada no dia 7 de agosto, quando a menina foi ao hospital, na cidade de São Mateus, se queixando de dores abdominais. A menina relatou que começou a ser estuprada pelo próprio tio desde que tinha 6 anos e que não o denunciou porque era ameaçada. Ele tem 33 anos e foi indiciado por estupro de vulnerável e ameaça, mas está foragido.
A Promotoria da Infância e da Juventude de São Mateus decidiu investigar se grupos tentaram pressionar a avó da menina para que o aborto não fosse autorizado. O MP também vai analisar áudios de conversas de pessoas que estariam pressionando a família da criança a não interromper a gravidez.
', 'https://g1.globo.com/pe/pernambuco/noticia/2020/08/17/menina-de-10-anos-estuprada-pelo-tio-no-es-tem-gravidez-interrompida.ghtml', 'https://s02.video.glbimg.com/640x360/8783097.jpg', 'Estrupo de vulnerável', '2020', 2020, true),

('Polícia procura por homem que matou a facadas a ex-mulher e a ex-sogra em festa de aniversário na Zona Leste de SP', '“A polícia procura Luís Felipe Oliveira, 29 anos, por ter matado a facadas a ex-mulher Nathalia Saldanha, durante uma festa na casa dela, em Guaianases, na Zona Leste de São Paulo, na noite desta segunda-feira (12). A mãe dela também morreu.
O carro usado por ele na fuga foi localizado pelos investigadores, mas a arma usada no crime ainda não foi encontrada. Luís invadiu o local e esfaqueou Nathalia; a mãe dela, Priscila Saldanha; o padrasto dela, Waldick Santos e mais duas pessoas que foram socorridas e liberadas. Santos segue internado e Priscila não resistiu aos ferimentos e morreu.
Na manhã antes do crime, Luís passou na casa de Nathalia para pegar a filha. Ele voltou à noite para cometer o crime. Segundo testemunhas, ele não aceitava o fim do relacionamento há pouco mais de um mês.”
', 'https://g1.globo.com/sp/sao-paulo/noticia/2020/10/13/policia-procura-por-homem-que-matou-a-facadas-a-ex-mulher-e-a-ex-sogra-em-festa-de-aniversario-na-zona-leste-de-sp.ghtml', 'https://s2-g1.glbimg.com/xkZSnzYaNqHO7CTfmEOuJh3yPAc=/696x390/smart/filters:cover():strip_icc()/s04.video.glbimg.com/x720/8937735.jpg', 'Feminicídio', '2020', 2020, false),

