--INSERTS de notícias pesquisadas


--Notícias de 1980
INSERT INTO news (title, description, link, image, category, decade, year, is_featured)
VALUES
('1980 o ano que ficou marcado como a décadas dos SERIAL KILLERS nos EUA:
', 'Durante três décadas da segunda metade do século 20, a América do Norte registrou um crescimento expressivo no número de homicídios em série, caracterizados por crimes semelhantes cometidos por um mesmo autor, os chamados serial killers. Esse aumento teve início nos anos 1960 e intensificou-se nas décadas seguintes, atingindo seu auge nos anos 1980, quando os casos se tornaram mais frequentes e notórios.', 'https://www.bbc.com/portuguese/internacional-45363043', 'Criminologia', 'anos 1980', 1980, TRUE),
('Um homem aparentemente inofensivo dos EUA: Ted Bundy', 'Jeffrey Dahmer, o Canibal de Milwaukee, matou 17 homens e garotos entre 1977 e 1991. Nascido em 1960, cometeu o primeiro assassinato aos 17 anos. Atraía vítimas para casa, onde cometia atos horríveis e desmembrava os corpos. Antes da prisão, teve problemas com a lei e foi expulso do exército. A série "Dahmer: Um canibal americano", de Ryan Murphy, estreia na Netflix.', 'https://f5.folha.uol.com.br/cinema-e-series/2022/10/jeffrey-dahmer-por-que-serie-sobre-serial-killer-americano-causa-tanta-polemica.shtml', 'Homicídio-qualificado', 'anos 1980', 1980, TRUE),
('O assassino em série que fez com que os palhaços nos aterrorizaram: John Wayne Gacy
', 'John Wayne Gacy, nascido em 1942 nos subúrbios de Chicago, teve uma infância marcada por abusos. Trabalhou em funerária, casou-se e virou gerente de restaurante, onde começou seus crimes. Em 1967, foi preso por abuso de menor, mas saiu após 16 meses. Enriquecido com sua empresa, criou o palhaço Pogo para eventos infantis, ocultando sua verdadeira face de predador sexual e assassino.', 'https://brasil.elpais.com/brasil/2019/06/28/actualidad/1561705341_083525.html', 'Serial Killers', 'anos 1980', 1980, TRUE),
('Alemanha condena ‘enfermeiro da morte’ que assassinou 85 pacientes', 'Niels Högel, enfermeiro alemão de 42 anos, foi condenado à prisão perpétua por matar 85 pacientes entre 2000 e 2005. A justiça considerou sua culpa "particularmente grave", anulando a chance de liberdade após 15 anos. Preso há 10 anos, Högel já havia sido condenado antes. É considerado o maior assassino em massa da Alemanha desde a Segunda Guerra.', 'https://brasil.elpais.com/brasil/2019/06/06/internacional/1559810905_905194.html#?rel=mas', 'Homicídio em série', 'anos 1980', 1980, TRUE),
('Assassinato de John Lennon: A Tragédia que Abalou o Mundo', 'Em 8 de dezembro de 1980, o ex-Beatle John Lennon foi assassinado a tiros por Mark David Chapman na entrada do edifício Dakota, em Nova York. Chapman, fã obcecado, alegou ter sido inspirado pelo livro "O Apanhador no Campo de Centeio". Lennon morreu a caminho do hospital, aos 40 anos.', 'https://people.com/john-lennon-death-what-to-know-7511226?utm_source=chatgpt.com', 'Assassinato', 'anos 1980', 1980, TRUE);

--Casos Famosos - Nacionais
INSERT INTO news (title, description, link, image, category, decade, year, is_featured)
('Elize Matsunaga: O crime e o castigo da mulher que matou e esquartejou o marido', 'Em 19 de maio de 2012, Elize Matsunaga matou seu marido, Marcos Kitano Matsunaga, após uma discussão sobre suas traições. Após o assassinato, Elize esquartejou o corpo e o colocou em malas de viagem, abandonando-o em uma rodovia. O crime foi descoberto quando o corpo foi encontrado e identificado em 23 de maio. O casal tinha uma relação conturbada e Elize agiu após desconfiar de mais traições.', 'https://oglobo.globo.com/blogs/blog-do-acervo/post/2023/02/elize-matsunaga-o-crime-e-o-castigo-da-mulher-que-matou-e-esquartejou-o-marido.ghtml', 'Feminicídio', 'anos 2010', 2010, TRUE),
('Isabela Nardoni: Alexandre Condenado por matar a filha, Nardoni é liberado para passar fim de ano na praia', 'Em março de 2008, Isabella Nardoni caiu da janela do 6º andar de um prédio em São Paulo, estando sob os cuidados do pai, Alexandre Nardoni, e da madrasta, Anna Carolina Jatobá. A investigação revelou que a menina foi agredida pela madrasta e jogada pela janela pelo pai. Ambos foram condenados em 2010: Alexandre a 31 anos e Anna a 26 anos e oito meses de prisão.', 'Em março de 2008, Isabella Nardoni caiu da janela do 6º andar de um prédio em São Paulo, estando sob os cuidados do pai, Alexandre Nardoni, e da madrasta, Anna Carolina Jatobá. A investigação revelou que a menina foi agredida pela madrasta e jogada pela janela pelo pai. Ambos foram condenados em 2010: Alexandre a 31 anos e Anna a 26 anos e oito meses de prisão.', 'Homicídio familiar.', 'anos 2000', 2008, TRUE),
('Caso Eloá', 'Em 13 de outubro de 2008, Lindemberg Alves sequestrou sua ex-namorada, Eloá, e a amiga Nayara, após o fim do relacionamento. Após quase 100 horas de cativeiro, a polícia invadiu o apartamento. Nayara foi libertada ferida, mas Eloá foi baleada na cabeça e na virilha, e teve a morte cerebral confirmada em 18 de outubro. O sequestrador foi capturado após a operação policial.', 'https://rollingstone.com.br/noticia/caso-eloa-producoes-para-entender-a-historia-que-chocou-o-pais/#google_vignette', 'Sequestro e Homicídio', 'anos 2000', 2008, TRUE),
('Ônibus 174', 'Em 12 de junho de 2000, Sandro Barbosa Nascimento sequestrou passageiros do ônibus 174 no Rio de Janeiro. A ação, transmitida ao vivo, durou mais de quatro horas e terminou com a morte de uma passageira, Geísa Firmo Gonçalves, e do sequestrador. Durante a abordagem, um policial do Bope disparou acidentalmente contra Geísa, que foi morta junto com o sequestrador minutos depois.', 'Em 12 de junho de 2000, Sandro Barbosa Nascimento sequestrou passageiros do ônibus 174 no Rio de Janeiro. A ação, transmitida ao vivo, durou mais de quatro horas e terminou com a morte de uma passageira, Geísa Firmo Gonçalves, e do sequestrador. Durante a abordagem, um policial do Bope disparou acidentalmente contra Geísa, que foi morta junto com o sequestrador minutos depois.', 'Sequestro', 'anos 2000', 2000, TRUE);

--Casos Famosos - Internacionais
INSERT INTO news (title, description, link, image, category, decade, year, is_featured)
('Mulher que matou 5 filhos é inocentada nos EUA', 'A americana Andrea Yates, que matou seus cinco filhos afogando-os em 2001, escapou da prisão perpétua em um segundo julgamento em 2006, após um júri aceitar que ela sofria de problemas mentais. Em 2002, ela foi condenada à prisão perpétua, mas alegou não estar mentalmente apta na época do crime. Ela foi enviada para um hospital psiquiátrico até ser considerada sã.', 'https://www.bbc.com/portuguese/noticias/story/2006/07/060726_yates_novojulgamentopu', 'Infanticídio', 'anos 2000', 2001, TRUE),
('A Dália Negra', 'A "Dália Negra", Elizabeth Short, uma aspirante a atriz de 23 anos, foi brutalmente assassinada e seu corpo encontrado em 15 de janeiro de 1947, em Los Angeles. A investigação revelou que ela passou seus últimos meses na zona sul da cidade, mas o crime nunca foi resolvido. A história ganhou fama mundial, sendo retratada em livros, filmes e games.', 'https://super.abril.com.br/mundo-estranho/o-que-foi-o-crime-da-dalia-negra/', 'Assassinato', 'anos 1940', 1947, TRUE),
('Há 129 anos, o caso Lizzie Borden escandalizava os Estados Unidos', 'https://aventurasnahistoria.com.br/noticias/reportagem/historia-crime-caso-lizzie-borden-assassinato.phtml', 'Duplo homicídio', 'anos 1890', 1892, TRUE),
('Deadpool Killer', 'Wade Wilson foi condenado à pena de morte pelo assassinato de Kristine Melton e Diane Ruiz em outubro de 2019, em Cape Coral, Flórida. Ele atacou também sua ex-namorada, Melissa Montanez. Em junho, um júri o considerou culpado de homicídios em primeiro grau e premeditados. Em 27 de junho, o juiz sentenciou Wilson à morte, após votação de jurados a favor da pena capital. As famílias das vítimas comemoraram a sentença.',  'https://aventurasnahistoria.com.br/noticias/historia-hoje/deadpool-killer-quem-saos-vitimas-do-homem-condenado-pena-de-morte.phtml', 'Homicídio duplo', 'anos 2010', 2019, TRUE);

--INSERTS de podcasts

INSERT INTO podcasts (title, description, link, image, category, is_featured)
VALUES 
('O Maníaco do Parque: Ullisses Campbel', 'Ullisses é escritor, e ele  vai contar histórias do livro que escreveu sobre o Maníaco do Parque, e como ele ludibriava as vítimas com sua moto. O Vilela nunca faria algo parecido, pois ele anda de patinete elétrico.', 'https://www.youtube.com/live/m_JMZDlVK9k?feature=shared', 'https://files.fm/u/bsqk5nqhs2', 'famoso', TRUE),
('Ilana Casoy', 'Ilana Casoy é escritora e expert em serial killers. Ilana tem como tema principal de seus livros os crimes de serial killers e assassinatos marcados pela perversidade, como os Nardoni e a Richthofen. O Vilela pensou em chamar a Richthofen para um papo, mas ela só estaria disponível no Dia das Mães.', 'https://www.youtube.com/live/YWaIk5BM3So?feature=shared', 'https://files.fm/u/42mzcw8dwq', 'antigo', TRUE),
('Crimes Reais: Ivan Mizanzuk', 'Ivan Mizanzuk é  professor universitário, designer, escritor, produtor de podcasts e jornalista. Ele conta “histórias reais de pessoas reais” no podcast Projeto Humanos. Já o Vilela só contrata projetos de humanos para trabalharem com ele.', 'https://youtu.be/UywLajXBLw4?feature=shared', 'https://files.fm/u/thfbuwngnx', 'reais', TRUE),
('Ela cuida das mentes mais pertubadas - Gabriela Cruz', 'Ela conhece a mente dos ped0filos! Gabriela Cruz é uma renomada psicóloga especialista em sexualidade humana. Antes de atender em clínicas, ela trabalhou durante anos em penitenciárias, acompanhando indivíduos condenados por ped0filia e outros cr1mes s3xuais', 'https://youtu.be/mdwQUT0i5dc?feature=shared', 'https://files.fm/u/ru4db2xayu', 'investigacao', TRUE),
('Crimes reais: Perita Rosangela Monteiro e Delegado Mauro Dias', 'Dra. Rosangela  é psicóloga e perita criminal, e MAURO DIAS é ex-delegado. Eles vão conversar sobre crimes reais e os processos de investigação e perícia para desvendar os casos. O Vilela é expert em esconder que comeu todo o chocolate da casa que nem um CSI São Paulo resolveria o caso.', 'https://www.youtube.com/live/28WQA1o1CDQ?feature=shared', 'https://files.fm/u/474xq2y5kf', 'investigação', TRUE);