--INSERTS de notícias pesquisadas


--Notícias de 1980
INSERT INTO news (title, description, text, link, image, category, decade, year, is_featured) VALUES
('1980 o ano que ficou marcado como a decada dos SERIAL KILLERS nos EUA', 'Entre as decadas de 1960 e 1980 a America do Norte teve um aumento marcante nos homicidios em serie com os serial killers ganhando destaque especialmente nos anos 1980.', 'Durante tres decadas da segunda metade do seculo 20 a America do Norte registrou um crescimento expressivo no numero de homicidios em serie caracterizados por crimes semelhantes cometidos por um mesmo autor os chamados serial killers. Esse aumento teve inicio nos anos 1960 e intensificou se nas decadas seguintes atingindo seu auge nos anos 1980 quando os casos se tornaram mais frequentes e notorios.', 'https://www.bbc.com/portuguese/internacional-45363043', 'https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/C5C9/production/_103233605_gettyimages-107654068.jpg.webp', 'Criminologia', 'anos 1980', 1980, TRUE),
('Um homem aparentemente inofensivo dos EUA Jeffrey Dahmer', 'Conhecido como o Canibal de Milwaukee matou e desmembrou 17 homens e garotos entre 1977 e 1991.', 'Jeffrey Dahmer o Canibal de Milwaukee matou 17 homens e garotos entre 1977 e 1991. Nascido em 1960 cometeu o primeiro assassinato aos 17 anos. Atraiu vitimas para casa onde cometia atos horriveis e desmembrava os corpos. Antes da prisao teve problemas com a lei e foi expulso do exercito.', 'https://f5.folha.uol.com.br/cinema-e-series/2022/10/jeffrey-dahmer-por-que-serie-sobre-serial-killer-americano-causa-tanta-polemica.shtml', 'https://s2-oglobo.glbimg.com/ehrDKfj-30VCdCPvz2JsZM9IrMs=/0x0:3600x1506/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2022/x/L/MseiC6S06oAW6RSLHVjQ/dahmer-season1-episode8-00-34-46-09r.jpg', 'Homicidio qualificado', 'anos 1980', 1980, TRUE),
('O assassino em serie que fez com que os palhacos nos aterrorizaram John Wayne Gacy', 'Assassinou dezenas de jovens enquanto se disfarçava de palhaco em festas infantis aterrorizando os EUA nos anos 1970.', 'John Wayne Gacy nascido em 1942 nos suburbios de Chicago teve uma infancia marcada por abusos. Trabalhou em funeraria casou se e virou gerente de restaurante onde comecou seus crimes. Em 1967 foi preso por abuso de menor mas saiu apos 16 meses. Enriquecido com sua empresa criou o palhaco Pogo para eventos infantis ocultando sua verdadeira face de predador sexual e assassino.', 'https://brasil.elpais.com/brasil/2019/06/28/actualidad/1561705341_083525.html', 'https://imagenes.elpais.com/resizer/v2/BOI3RQ5IQEUQJVWVFV4PXQZW7A.jpg?auth=7fb606bf8587f56d1cd517f58f4e6d222c99ef65865f299e1371ea5e72e2cd90&width=1960&height=1470&smart=true', 'Serial Killers', 'anos 1980', 1980, TRUE),
('Alemanha condena enfermeiro da morte que assassinou 85 pacientes', 'Enfermeiro alemao condenado pelo assassinato de 85 pacientes tornando se um dos maiores assassinos em serie da historia da Alemanha.', 'Niels Hogel enfermeiro alemao de 42 anos foi condenado a prisao perpetua por matar 85 pacientes entre 2000 e 2005. A justica considerou sua culpa particularmente grave anulando a chance de liberdade apos 15 anos. Preso ha 10 anos Hogel ja havia sido condenado antes. E considerado o maior assassino em massa da Alemanha desde a Segunda Guerra.', 'https://brasil.elpais.com/brasil/2019/06/06/internacional/1559810905_905194.html#?rel=mas', 'https://s2-g1.glbimg.com/QI4GuWtFFw5oFfjS-jmxDIouNhM=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2019/j/9/sh0ASCT4qucopU45NG0A/2019-06-06t085211z-715565607-rc1d45909910-rtrmadp-3-germany-crime-nurse.jpg', 'Homicidio em serie', 'anos 1980', 1980, TRUE),
('Assassinato de John Lennon A Tragedia que Abalou o Mundo', 'O ex Beatle foi morto a tiros por Mark David Chapman em 1980 chocando o mundo.', 'Em 8 de dezembro de 1980 o ex Beatle John Lennon foi assassinado a tiros por Mark David Chapman na entrada do edificio Dakota em Nova York. Chapman fa obcecado alegou ter sido inspirado pelo livro O Apanhador no Campo de Centeio. Lennon morreu a caminho do hospital aos 40 anos.', 'https://people.com/john-lennon-death-what-to-know-7511226?utm_source=chatgpt.com', 'https://people.com/thmb/tfy6---qV_LOneVOGcobI3lcsTs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(993x544:995x546)/john-lennon-1-b6149af014914b19b37a612eada10658.jpg', 'Assassinato', 'anos 1980', 1980, TRUE);

--Casos Famosos - Nacionais
INSERT INTO news (title, description, text, link, image, category, decade, year, is_featured) VALUES
('Elize Matsunaga O crime e o castigo da mulher que matou e esquartejou o marido', 'Em 2012 matou e esquartejou o marido apos discussao sobre traicoes chocando o pais.', 'Em 19 de maio de 2012 Elize Matsunaga matou seu marido Marcos Kitano Matsunaga apos uma discussao sobre suas traicoes. Apos o assassinato Elize esquartejou o corpo e o colocou em malas de viagem abandonando o em uma rodovia. O crime foi descoberto quando o corpo foi encontrado e identificado em 23 de maio. O casal tinha uma relacao conturbada e Elize agiu apos desconfiar de mais traicoes.', 'https://oglobo.globo.com/blogs/blog-do-acervo/post/2023/02/elize-matsunaga-o-crime-e-o-castigo-da-mulher-que-matou-e-esquartejou-o-marido.ghtml', 'https://cloudfront-us-east-1.images.arcpublishing.com/estadao/NYRIQGEPBJNKJCKLL3KAMDZB6E.jpg', 'Feminicidio', 'anos 2010', 2010, TRUE),
('Isabela Nardoni Alexandre Condenado por matar a filha Nardoni e liberado para passar fim de ano na praia', 'Menina de 5 anos foi jogada do sexto andar pelo pai e pela madrasta que foram condenados pelo crime.', 'Em marco de 2008 Isabella Nardoni caiu da janela do 6 andar de um predio em Sao Paulo estando sob os cuidados do pai Alexandre Nardoni e da madrasta Anna Carolina Jatoba. A investigacao revelou que a menina foi agredida pela madrasta e jogada pela janela pelo pai. Ambos foram condenados em 2010 Alexandre a 31 anos e Anna a 26 anos e oito meses de prisao.', 'https://www.cnnbrasil.com.br/nacional/sudeste/sp/morta-em-2008-isabella-nardoni-faria-23-anos-e-mae-faz-homenagem-veja/', 'https://p2.trrsf.com/image/fget/cf/774/0/images.terra.com/2023/08/21/ana-carolina-e-isabela-u7u1zfj7h17o.PNG', 'Homicidio familiar', 'anos 2000', 2008, TRUE),
('Caso Eloa', 'Sequestro e morte de Eloa Pimentel pelo ex namorado apos quase 100 horas de cativeiro em 2008.', 'Em 13 de outubro de 2008 Lindemberg Alves sequestrou sua ex namorada Eloa e a amiga Nayara apos o fim do relacionamento. Apos quase 100 horas de cativeiro a policia invadiu o apartamento. Nayara foi libertada ferida mas Eloa foi baleada na cabeca e na virilha e teve a morte cerebral confirmada em 18 de outubro. O sequestrador foi capturado apos a operacao policial.', 'https://rollingstone.com.br/noticia/caso-eloa-producoes-para-entender-a-historia-que-chocou-o-pais/#google_vignette', 'https://rollingstone.com.br/media/_versions/2023/05/caso-eloa-linha-direta-globo-foto-reproducao_widelg.jpg', 'Sequestro e Homicidio', 'anos 2000', 2008, TRUE),
('Onibus 174', 'Sequestro de onibus no Rio de Janeiro em 2000 terminou tragicamente com a morte de uma refem e do sequestrador diante das cameras.', 'Em 12 de junho de 2000 Sandro Barbosa Nascimento sequestrou passageiros do onibus 174 no Rio de Janeiro. A acao transmitida ao vivo durou mais de quatro horas e terminou com a morte de uma passageira Geisa Firmo Goncalves e do sequestrador. Durante a abordagem um policial do Bope disparou acidentalmente contra Geisa que foi morta junto com o sequestrador minutos depois.', 'https://www.cnnbrasil.com.br/nacional/sequestro-do-onibus-174-no-rio-em-2000-durou-quase-4-horas/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2024/03/onibus7.183501.jpg?w=1200&h=1200&crop=1', 'Sequestro', 'anos 2000', 2000, TRUE);

--Casos Famosos - Internacionais
INSERT INTO news (title, description, text, link, image, category, decade, year, is_featured) VALUES
('Mulher que matou 5 filhos e inocentada nos EUA', 'Americana que matou seus cinco filhos em 2001 considerada inimputavel devido a problemas mentais.', 'A americana Andrea Yates que matou seus cinco filhos afogando os em 2001 escapou da prisao perpetua em um segundo julgamento em 2006 apos um juri aceitar que ela sofria de problemas mentais. Em 2002 ela foi condenada a prisao perpetua mas alegou nao estar mentalmente apta na epoca do crime. Ela foi enviada para um hospital psiquiatrico ate ser considerada san.', 'https://www.bbc.com/portuguese/noticias/story/2006/07/060726_yates_novojulgamentopu', 'https://www.bbc.com/staticarchive/5e7baf5cf2fa8ec69dd9e2cf468f8451c50f7faf.jpg', 'Infanticidio', 'anos 2000', 2001, TRUE),
('A Dalia Negra', 'Elizabeth Short aspirante a atriz foi brutalmente assassinada em 1947 em Los Angeles crime nunca solucionado.', 'A Dalia Negra Elizabeth Short uma aspirante a atriz de 23 anos foi brutalmente assassinada e seu corpo encontrado em 15 de janeiro de 1947 em Los Angeles. A investigacao revelou que ela passou seus ultimos meses na zona sul da cidade mas o crime nunca foi resolvido. A historia ganhou fama mundial sendo retratada em livros filmes e games.', 'https://super.abril.com.br/mundo-estranho/o-que-foi-o-crime-da-dalia-negra/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxkIQMxRS9DpqelJLkOZK8MgqDg23po6HY9w&s', 'Assassinato', 'anos 1940', 1947, TRUE),
('Ha 129 anos o caso Lizzie Borden escandalizava os Estados Unidos', 'Caso escandaloso nos EUA de 1892 quando Lizzie foi acusada do assassinato dos proprios pais com um machado.', 'Lizzie Borden foi acusada de matar o pai e a madrasta a machadadas em 1892. A policia encontrou armas suspeitas mas nada foi comprovado. Lizzie queimou um vestido levantando suspeitas mas acabou inocentada por falta de provas. O caso nunca foi solucionado gerando varias teorias. Isolada pela sociedade viveu em Fall River ate morrer em 1927.', 'https://aventurasnahistoria.com.br/noticias/reportagem/historia-crime-caso-lizzie-borden-assassinato.phtml', 'https://aventurasnahistoria.com.br/media/_versions/lizziebordeninocente_widelg.jpeg', 'Duplo homicidio', 'anos 1890', 1892, TRUE),
('Deadpool Killer', 'Condenado a morte pelo assassinato de duas mulheres na Florida em 2019.', 'Wade Wilson foi condenado a pena de morte pelo assassinato de Kristine Melton e Diane Ruiz em outubro de 2019 em Cape Coral Florida. Ele atacou tambem sua ex namorada Melissa Montanez. Em junho um juri o considerou culpado de homicidios em primeiro grau e premeditados. Em 27 de junho o juiz sentenciou Wilson a morte apos votacao de jurados a favor da pena capital. As familias das vitimas comemoraram a sentenca.',  'https://aventurasnahistoria.com.br/noticias/historia-hoje/deadpool-killer-quem-saos-vitimas-do-homem-condenado-pena-de-morte.phtml', 'https://aventurasnahistoria.com.br/media/_versions/2024/08/deadpoolkiller4_widelg.jpg', 'Homicidio duplo', 'anos 2010', 2019, TRUE);

--INSERTS de podcasts

INSERT INTO podcasts (title, description, text, link, image, category, is_featured)
VALUES 
('O Maníaco do Parque: Ullisses Campbel', 'Ullisses é escritor, e ele  vai contar histórias do livro que escreveu sobre o Maníaco do Parque, e como ele ludibriava as vítimas com sua moto. O Vilela nunca faria algo parecido, pois ele anda de patinete elétrico.', 'https://www.youtube.com/live/m_JMZDlVK9k?feature=shared', 'https://files.fm/u/bsqk5nqhs2', 'famoso', TRUE),
('Ilana Casoy', 'Ilana Casoy é escritora e expert em serial killers. Ilana tem como tema principal de seus livros os crimes de serial killers e assassinatos marcados pela perversidade, como os Nardoni e a Richthofen. O Vilela pensou em chamar a Richthofen para um papo, mas ela só estaria disponível no Dia das Mães.', 'https://www.youtube.com/live/YWaIk5BM3So?feature=shared', 'https://files.fm/u/42mzcw8dwq', 'antigo', TRUE),
('Crimes Reais: Ivan Mizanzuk', 'Ivan Mizanzuk é  professor universitário, designer, escritor, produtor de podcasts e jornalista. Ele conta “histórias reais de pessoas reais” no podcast Projeto Humanos. Já o Vilela só contrata projetos de humanos para trabalharem com ele.', 'https://youtu.be/UywLajXBLw4?feature=shared', 'https://files.fm/u/thfbuwngnx', 'reais', TRUE),
('Ela cuida das mentes mais pertubadas - Gabriela Cruz', 'Ela conhece a mente dos ped0filos! Gabriela Cruz é uma renomada psicóloga especialista em sexualidade humana. Antes de atender em clínicas, ela trabalhou durante anos em penitenciárias, acompanhando indivíduos condenados por ped0filia e outros cr1mes s3xuais', 'https://youtu.be/mdwQUT0i5dc?feature=shared', 'https://files.fm/u/ru4db2xayu', 'investigacao', TRUE),
('Crimes reais: Perita Rosangela Monteiro e Delegado Mauro Dias', 'Dra. Rosangela  é psicóloga e perita criminal, e MAURO DIAS é ex-delegado. Eles vão conversar sobre crimes reais e os processos de investigação e perícia para desvendar os casos. O Vilela é expert em esconder que comeu todo o chocolate da casa que nem um CSI São Paulo resolveria o caso.', 'https://www.youtube.com/live/28WQA1o1CDQ?feature=shared', 'https://files.fm/u/474xq2y5kf', 'investigação', TRUE);

    --decadas de 80
  INSERT INTO news (title, description, text, link, image, category, decade, year, is_featured)
VALUES 
('1980: O ano que ficou marcado como a decada dos SERIAL KILLERS nos EUA',
'Durante tres decadas da segunda metade do seculo 2020, a America do Norte registrou um crescimento expressivo no numero de homicidios em serie, caracterizados por crimes semelhantes cometidos por um mesmo autor, os chamados serial killers.',
'Washington 10 de junho de 2025. O ano de 1980 e mais amplamente a decada de 1980 ficou para sempre marcado na historia dos Estados Unidos como o periodo mais sombrio no que diz respeito a proliferacao de serial killers. Foi uma epoca em que o medo permeava as ruas e a midia popularizou o termo serial killer cunhado pelo FBI para descrever criminosos que cometiam assassinatos em serie com intervalos de tempo entre os crimes.Nos anos 80 os EUA enfrentavam uma combinacao de fatores que segundo especialistas contribuiram para o aumento da atividade desses assassinos em serie.Movimentacao massiva de pessoas entre estados dificultando o rastreamento de criminosos.
Deficiencias tecnologicas nas investigacoes forenses.Mudancas culturais e sociais que criavam tanto vitimas vulneraveis quanto criminosos oportunistas.Ted Bundy executado em 1989 confessou mais de 30 assassinatos embora o numero real permaneça desconhecido.
John Wayne Gacy condenado por matar pelo menos 33 jovens e enterra-los sob sua casa capturado em 1978 e executado em 1994.
Richard Ramirez Night Stalker aterrorizou a California em meados da decada.
Gary Ridgway Green River Killer embora so tenha sido preso em 2001 cometeu muitos de seus crimes na decada de 1980.
David Berkowitz Son of Sam preso em 1977 mas seu caso e cobertura midiática impulsionaram a paranoia no inicio da decada.',
'https://www.bbc.com/portuguese/internacional-45363043',
'SerialKillers.jpeg',
'Criminologia', '80', 1980, TRUE),

('Um homem aparentemente inofensivo dos EUA: Ted Bundy',
'Jeffrey Dahmer, o Canibal de Milwaukee, matou 17 homens e garotos entre 1977 e 1991. Nascido em 1960, cometeu o primeiro assassinato aos 17 anos.',
'Atraia suas vitimas para sua casa, utilizando diferentes artifcios e estrategias para conquistar sua confianca, como promessas de empregos, ofertas de ajuda ou ate mesmo convites para eventos sociais. Ao chegarem ao local, as vitimas eram surpreendidas por sua verdadeira intencao: cometia atos horriveis, envolvendo violencia extrema, tortura psicologica e fisica, alem de abusos de varias naturezas. Ele demonstrava uma crueldade incomum, prolongando o sofrimento de suas vitimas antes de desmembrar os corpos de maneira meticulosa, evidenciando um grau assustador de frieza e falta de empatia. Apos cometer esses crimes brutais, ele se dedicava a ocultar cuidadosamente as provas, espalhando partes dos corpos em locais remotos, enterrando restos mortais em seu proprio quintal ou ate mesmo mantendo fragmentos como trofeus macabros. Sua habilidade em manipular e enganar pessoas dificultou por muito tempo as investigacoes policiais, fazendo com que permanecesse impune por anos. Antes de ser finalmente capturado, ja havia tido varios problemas com a lei, incluindo envolvimento em pequenos delitos e comportamentos suspeitos. Sua passagem pelo exercito tambem foi marcada por episodios de indisciplina, agressividade e desrespeito as regras, fatores que contribuiram para sua expulsao da instituicao militar. Esse historico de transgressoes, associado a sua personalidade fria e calculista, permitiu que ele continuasse a agir sem levantar grandes suspeitas, ate que suas atrocidades vieram a tona, chocando toda a sociedade.',
'https://f5.folha.uol.com.br/cinema-e-series/202022/10/jeffrey-dahmer-por-que-serie-sobre-serial-killer-americano-causa-tanta-polemica.shtml',
'JeffreyDahmer.jpg',
'Homicidio Qualificado', '80', 1980, TRUE),

('O assassino em serie que fez com que os palhacos nos aterrorizassem: John Wayne Gacy',
'John Wayne Gacy, nascido em 1942 nos suburbios de Chicago, teve uma infancia marcada por abusos. Trabalhou em funeraria, casou-se e virou gerente de restaurante, onde comecou seus crimes.',
'John Wayne Gacy ficou conhecido como o "Palhaco Assassino" e, durante os anos 1970, chocou os Estados Unidos com seus crimes. Entre 1972 e 1978, Gacy sequestrou, torturou e assassinou ao menos 33 jovens, a maioria garotos e adolescentes. Muitos de seus crimes foram cometidos em sua propria casa, onde escondia os corpos das vitimas sob o assoalho.

O modus operandi de Gacy consistia em atrair suas vitimas com promessas de trabalho, dinheiro facil ou ate mesmo aproveitando-se de sua imagem amigavel como palhaco em festas infantis. Apos conquistar a confianca dos jovens, Gacy revelava sua verdadeira natureza, cometendo os assassinatos de maneira brutal.

A investigacao que levou a sua prisao comecou apos o desaparecimento de um adolescente, cujo ultimo paradeiro conhecido era justamente um encontro com Gacy. A policia descobriu provas contundentes em sua casa, culminando na prisao e confissao dos crimes. O caso teve enorme repercussao midiática, principalmente pelo contraste entre seu papel de animador de festas e sua crueldade.

Condenado a morte, John Wayne Gacy foi executado em 1994. Sua historia permanece como um dos maiores exemplos de serial killers nos EUA e reforcou o estigma do palhaco como figura assustadora, inspirando livros, filmes e documentarios sobre sua trajetoria macabra.',
'https://brasil.elpais.com/brasil/202019/06/28/actualidad/1561705341_083525.html',
'JohnWayne.jpeg',
'Serial Killers', '80', 1980, TRUE),

('Alemanha condena enfermeiro da morte que assassinou 85 pacientes',
'Niels Hogel, enfermeiro alemao de 42 anos, foi condenado a prisao perpetua por matar 85 pacientes entre 202000 e 202005.',
'O caso do enfermeiro Niels Hogel ganhou grande repercussao na Alemanha e internacionalmente por sua extrema gravidade e pelo numero elevado de vitimas. Hogel trabalhava em dois hospitais no norte da Alemanha, em Oldenburg e Delmenhorst, onde, entre 2000 e 2005, administrou intencionalmente doses letais de medicamentos em pacientes internados. O objetivo declarado por ele era provocar paradas cardiacas para, em seguida, tentar reanimar as vitimas e demonstrar suas habilidades medicas. No entanto, muitas vezes, os pacientes nao sobreviviam.
As investigacoes mostraram que as mortes incomuns so comecaram a levantar suspeitas apos varios anos. O numero oficial de vitimas confirmadas chegou a 85, mas autoridades estimam que o total pode ser ainda maior, ja que nem todos os corpos puderam ser exumados ou analisados. Durante o julgamento, Hogel confessou muitos dos assassinatos e demonstrou remorso, mas familiares das vitimas relataram sentimentos de revolta e indignacao.
O tribunal classificou a culpa de Hogel como particularmente grave, o que significa que ele nao podera pedir liberdade condicional apos 15 anos de prisao, como normalmente preve a lei alema. Ele recebeu a pena maxima permitida no pais. O caso tambem gerou discussoes profundas sobre falhas sistemicas na supervisao hospitalar e na cultura de denuncia, ja que colegas e superiores ignoraram sinais de alerta por anos, o que pode ter contribuido para a continuidade dos crimes.
A sociedade alema ficou chocada com a extensao dos assassinatos e com a facilidade com que Hogel conseguiu agir sem ser detectado por tanto tempo. O caso e considerado o maior massacre cometido por um individuo na Alemanha desde a Segunda Guerra Mundial e levantou questionamentos sobre a seguranca dos pacientes nos hospitais do pais.',
'https://brasil.elpais.com/brasil/202019/06/06/internacional/1559810905_905194.html',
'NielsHogel.jpeg',
'Homicidio em Serie', '80', 1980, TRUE),

('Assassinato de John Lennon: A Tragedia que Abalou o Mundo',
'Em 8 de dezembro de 1980, o ex-Beatle John Lennon foi assassinado a tiros por Mark David Chapman na entrada do edificio Dakota, em Nova York.',
'No dia 8 de dezembro de 1980, o mundo foi surpreendido por uma noticia devastadora: John Lennon, ex-integrante da lendaria banda The Beatles, foi assassinado a tiros em Nova York. O crime aconteceu na entrada do edificio Dakota, onde Lennon morava com sua esposa, Yoko Ono.
Naquela noite, Lennon voltava para casa apos uma sessao de gravacao. Mark David Chapman, um fa obcecado, ja o aguardava em frente ao predio. Mais cedo naquele dia, Chapman havia conseguido um autografo de Lennon. Quando Lennon retornou ao Dakota por volta das 22h50, Chapman se aproximou e disparou cinco vezes, acertando Lennon quatro vezes nas costas e no ombro. O musico foi rapidamente levado ao Hospital Roosevelt, mas chegou sem vida. Ele tinha apenas 40 anos de idade.
Mark David Chapman era um jovem perturbado do Hawai, que alegou ter sido inspirado pelo livro "O Apanhador no Campo de Centeio", de J.D. Salinger. Segundo ele, vozes em sua cabeca e uma fixacao pelo livro o motivaram a cometer o crime. Apos atirar em Lennon, Chapman permaneceu no local, lendo calmamente o romance enquanto aguardava a chegada da policia, a qual se entregou sem resistir.
A morte de John Lennon provocou uma comoção mundial. Milhares de fas se reuniram em vigilias em frente ao edificio Dakota, no Central Park e em varios lugares do mundo para prestar homenagens ao musico. Lennon era mais do que um ex-Beatle: era simbolo de paz, ativismo e liberdade de expressao. Seu assassinato reacendeu debates sobre o controle de armas nos Estados Unidos e o perigo da obsessao de fas por celebridades.
O legado de John Lennon permanece vivo ate hoje, seja por sua musica, sua mensagem de paz ou pela influencia cultural que exerceu. O crime interrompeu de forma brutal uma das trajetorias mais marcantes da historia da musica, e ate hoje e lembrado como um dos episodios mais tragicos do seculo XX.',
'https://people.com/john-lennon-death-what-to-know-7511226',
'John_Lennon.jpeg',
'Assassinato', '80', 1980, TRUE);